
quarkus.http.host = 0.0.0.0
quarkus.http.port = 8082

quarkus.datasource.jdbc.url = jdbc:mysql://localhost:3306/eshop_quarkus?createDatabaseIfNotExist=true
quarkus.datasource.username = root
quarkus.datasource.password = root

quarkus.hibernate-orm.schema-management.strategy = update
quarkus.hibernate-orm.log.sql = true


